# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'buttonTapTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for buttonTapTest

  target 'buttonTapTestTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxSwift', '6.1.0'
    pod 'RxCocoa', '6.1.0'
  end

  target 'buttonTapTestUITests' do
    # Pods for testing
    pod 'RxBlocking', '6.1.0'
    pod 'RxTest', '6.1.0'
  end

end
